Fix Qt 5.15 deprecation warnings
These fixes have been placed under a QT_VERSION ifdef because the
replacement functions were introduced in Qt 5.14/5.15 and Debian/Ubuntu
is still on Qt 5.12.

src/gui-qt/common/graphics/zoomablegraphicsview.cpp: In member function ‘virtual void UnTech::GuiQt::ZoomableGraphicsView::wheelEvent(QWheelEvent*)’:
src/gui-qt/common/graphics/zoomablegraphicsview.cpp:62:59: error: ‘QPoint QWheelEvent::pos() const’ is deprecated: Use position() [-Werror=deprecated-declarations]
   62 |         const QPointF oldScenePos = mapToScene(event->pos());
      |                                                           ^
In file included from /usr/include/qt/QtGui/QWheelEvent:1,
                 from src/gui-qt/common/graphics/zoomablegraphicsview.cpp:11:
/usr/include/qt/QtGui/qevent.h:225:19: note: declared here
  225 |     inline QPoint pos() const { return p.toPoint(); }
      |                   ^~~
src/gui-qt/common/graphics/zoomablegraphicsview.cpp:72:45: error: ‘QPoint QWheelEvent::pos() const’ is deprecated: Use position() [-Werror=deprecated-declarations]
   72 |             const QPoint delta = event->pos() - mapFromScene(oldScenePos);
      |                                             ^
In file included from /usr/include/qt/QtGui/QWheelEvent:1,
                 from src/gui-qt/common/graphics/zoomablegraphicsview.cpp:11:
/usr/include/qt/QtGui/qevent.h:225:19: note: declared here
  225 |     inline QPoint pos() const { return p.toPoint(); }
      |                   ^~~
cc1plus: all warnings being treated as errors
make: *** [GNUmakefile:354: obj/debug-g++/gui-qt/common/graphics/zoomablegraphicsview.o] Error 1

g++ -std=c++17 -g -Og -MMD -Isrc -Werror -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC -gsplit-dwarf -D_GLIBCXX_ASSERTIONS -fasynchronous-unwind-tables -fexceptions -fpic -fpie -fstack-protector-strong -pipe -Wall -Wextra -Wdeprecated -Wvla -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/qt/QtGui -I/usr/include/qt/QtWidgets -DQT_SVG_LIB -I/usr/include/qt/QtSvg -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB  -fPIC -Igen -c -o obj/debug-g++/gui-qt/metasprite/metasprite/palettesdock.o src/gui-qt/metasprite/metasprite/palettesdock.cpp
src/gui-qt/metasprite/metasprite/palettesdock.cpp: In constructor ‘UnTech::GuiQt::MetaSprite::MetaSprite::PalettesDock::PalettesDock(QWidget*)’:
src/gui-qt/metasprite/metasprite/palettesdock.cpp:70:69: error: ‘void QButtonGroup::buttonClicked(int)’ is deprecated: Use QButtonGroup::idClicked(int) instead [-Werror=deprecated-declarations]
   70 |     connect(_colorGroup, qOverload<int>(&QButtonGroup::buttonClicked),
      |                                                                     ^
In file included from /usr/include/qt/QtWidgets/QButtonGroup:1,
                 from src/gui-qt/metasprite/metasprite/palettesdock.h:10,
                 from src/gui-qt/metasprite/metasprite/palettesdock.cpp:7:
/usr/include/qt/QtWidgets/qbuttongroup.h:90:10: note: declared here
   90 |     void buttonClicked(int);
      |          ^~~~~~~~~~~~~
src/gui-qt/metasprite/metasprite/palettesdock.cpp:70:69: error: ‘void QButtonGroup::buttonClicked(int)’ is deprecated: Use QButtonGroup::idClicked(int) instead [-Werror=deprecated-declarations]
   70 |     connect(_colorGroup, qOverload<int>(&QButtonGroup::buttonClicked),
      |                                                                     ^
In file included from /usr/include/qt/QtWidgets/QButtonGroup:1,
                 from src/gui-qt/metasprite/metasprite/palettesdock.h:10,
                 from src/gui-qt/metasprite/metasprite/palettesdock.cpp:7:
/usr/include/qt/QtWidgets/qbuttongroup.h:90:10: note: declared here
   90 |     void buttonClicked(int);
      |          ^~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make: *** [GNUmakefile:351: obj/debug-g++/gui-qt/metasprite/metasprite/palettesdock.o] Error 1

g++ -std=c++17 -g -Og -MMD -Isrc -Werror -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC -gsplit-dwarf -D_GLIBCXX_ASSERTIONS -fasynchronous-unwind-tables -fexceptions -fpic -fpie -fstack-protector-strong -pipe -Wall -Wextra -Wdeprecated -Wvla -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/qt/QtGui -I/usr/include/qt/QtWidgets -DQT_SVG_LIB -I/usr/include/qt/QtSvg -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB  -fPIC -Igen -c -o obj/debug-g++/gui-qt/metatiles/mttileset/editorwidget.o src/gui-qt/metatiles/mttileset/editorwidget.cpp
src/gui-qt/metatiles/mttileset/editorwidget.cpp: In constructor ‘UnTech::GuiQt::MetaTiles::MtTileset::EditorWidget::EditorWidget(UnTech::GuiQt::ZoomSettingsManager*, QWidget*)’:
src/gui-qt/metatiles/mttileset/editorwidget.cpp:100:74: error: ‘void QComboBox::activated(const QString&)’ is deprecated: Use textActivated() instead [-Werror=deprecated-declarations]
  100 |     connect(_ui->palette, qOverload<const QString&>(&QComboBox::activated),
      |                                                                          ^
In file included from /usr/include/qt/QtWidgets/QComboBox:1,
                 from src/gui-qt/common/graphics/zoomsettings.h:9,
                 from src/gui-qt/common/graphics/zoomsettingsmanager.h:9,
                 from src/gui-qt/metatiles/mttileset/editorwidget.cpp:13:
/usr/include/qt/QtWidgets/qcombobox.h:245:10: note: declared here
  245 |     void activated(const QString &);
      |          ^~~~~~~~~
src/gui-qt/metatiles/mttileset/editorwidget.cpp:100:74: error: ‘void QComboBox::activated(const QString&)’ is deprecated: Use textActivated() instead [-Werror=deprecated-declarations]
  100 |     connect(_ui->palette, qOverload<const QString&>(&QComboBox::activated),
      |                                                                          ^
In file included from /usr/include/qt/QtWidgets/QComboBox:1,
                 from src/gui-qt/common/graphics/zoomsettings.h:9,
                 from src/gui-qt/common/graphics/zoomsettingsmanager.h:9,
                 from src/gui-qt/metatiles/mttileset/editorwidget.cpp:13:
/usr/include/qt/QtWidgets/qcombobox.h:245:10: note: declared here
  245 |     void activated(const QString &);
      |          ^~~~~~~~~
cc1plus: all warnings being treated as errors
make: *** [GNUmakefile:351: obj/debug-g++/gui-qt/metatiles/mttileset/editorwidget.o] Error 1

g++ -std=c++17 -g -Og -MMD -Isrc -Werror -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC -gsplit-dwarf -D_GLIBCXX_ASSERTIONS -fasynchronous-unwind-tables -fexceptions -fpic -fpie -fstack-protector-strong -pipe -Wall -Wextra -Wdeprecated -Wvla -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/qt/QtGui -I/usr/include/qt/QtWidgets -DQT_SVG_LIB -I/usr/include/qt/QtSvg -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB  -fPIC -Igen -c -o obj/debug-g++/gui-qt/metatiles/mttileset/tilepropertieswidget.o src/gui-qt/metatiles/mttileset/tilepropertieswidget.cpp
src/gui-qt/metatiles/mttileset/tilepropertieswidget.cpp: In constructor ‘UnTech::GuiQt::MetaTiles::MtTileset::TilePropertiesWidget::TilePropertiesWidget(QWidget*)’:
src/gui-qt/metatiles/mttileset/tilepropertieswidget.cpp:78:79: error: ‘void QButtonGroup::buttonClicked(int)’ is deprecated: Use QButtonGroup::idClicked(int) instead [-Werror=deprecated-declarations]
   78 |     connect(_collisionTypeButtons, qOverload<int>(&QButtonGroup::buttonClicked),
      |                                                                               ^
In file included from /usr/include/qt/QtWidgets/QButtonGroup:1,
                 from src/gui-qt/metatiles/mttileset/tilepropertieswidget.cpp:13:
/usr/include/qt/QtWidgets/qbuttongroup.h:90:10: note: declared here
   90 |     void buttonClicked(int);
      |          ^~~~~~~~~~~~~
src/gui-qt/metatiles/mttileset/tilepropertieswidget.cpp:78:79: error: ‘void QButtonGroup::buttonClicked(int)’ is deprecated: Use QButtonGroup::idClicked(int) instead [-Werror=deprecated-declarations]
   78 |     connect(_collisionTypeButtons, qOverload<int>(&QButtonGroup::buttonClicked),
      |                                                                               ^
In file included from /usr/include/qt/QtWidgets/QButtonGroup:1,
                 from src/gui-qt/metatiles/mttileset/tilepropertieswidget.cpp:13:
/usr/include/qt/QtWidgets/qbuttongroup.h:90:10: note: declared here
   90 |     void buttonClicked(int);
      |          ^~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make: *** [GNUmakefile:351: obj/debug-g++/gui-qt/metatiles/mttileset/tilepropertieswidget.o] Error 1