Fix "size_t has not been declared" compile error
> make
g++ -MMD -MP -std=c++17 -O2 -flto -fdata-sections -ffunction-sections -Isrc -D_FORTIFY_SOURCE=2 -D_GLIBCXX_ASSERTIONS -fasynchronous-unwind-tables -fexceptions -fpic -fpie -fstack-protector-strong -pipe -Wall -Wextra -Wdeprecated -Wvla -c -o obj/release/models/snes/tile-data.o src/models/snes/tile-data.cpp
In file included from src/models/snes/tile-data.cpp:7:
src/models/snes/tile-data.h:14:11: error: ‘size_t’ has not been declared
   14 | template <size_t TS>
      |           ^~~~~~