Fix warning when compiling with g++
$ make PROFILE=debug CXX=g++

g++ -std=c++14 -g -MMD -Isrc -Werror -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC -gsplit-dwarf  -D_GLIBCXX_ASSERTIONS -fasynchronous-unwind-tables -fexceptions -fpic -fpie -fstack-protector-strong -pipe -fstack-clash-protection -Wall -Wextra -Wdeprecated -Wduplicated-cond -Wduplicated-branches -Wlogical-op -Wrestrict -Wnull-dereference -Wdouble-promotion -Wformat=2 -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/qt/QtGui -I/usr/include/qt/QtWidgets -DQT_SVG_LIB -I/usr/include/qt/QtSvg -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB  -fPIC -Igen -c -o obj/debug-g++/gui-qt/accessor/listactions.o src/gui-qt/accessor/listactions.cpp
src/gui-qt/accessor/listactions.cpp: In member function ‘void UnTech::GuiQt::Accessor::ListActions::updateActions_multipleSelection()’:
src/gui-qt/accessor/listactions.cpp:177:69: error: comparison of unsigned expression >= 0 is always true [-Werror=type-limits]
     const bool selectionValid = !indexes.empty() && indexes.front() >= 0 && indexes.back() < listSize;
                                                     ~~~~~~~~~~~~~~~~^~~~
cc1plus: all warnings being treated as errors
make: *** [GNUmakefile:356: obj/debug-g++/gui-qt/accessor/listactions.o] Error 1

g++ -std=c++14 -g -MMD -Isrc -Werror -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC -gsplit-dwarf  -D_GLIBCXX_ASSERTIONS -fasynchronous-unwind-tables -fexceptions -fpic -fpie -fstack-protector-strong -pipe -fstack-clash-protection -Wall -Wextra -Wdeprecated -Wduplicated-cond -Wduplicated-branches -Wlogical-op -Wrestrict -Wnull-dereference -Wdouble-promotion -Wformat=2 -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/qt/QtGui -I/usr/include/qt/QtWidgets -DQT_SVG_LIB -I/usr/include/qt/QtSvg -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB  -fPIC -Igen -c -o obj/debug-g++/gui-qt/accessor/multilistactions.o src/gui-qt/accessor/multilistactions.cpp
src/gui-qt/accessor/multilistactions.cpp: In member function ‘void UnTech::GuiQt::Accessor::MultiListActions::updateActions()’:
src/gui-qt/accessor/multilistactions.cpp:178:73: error: comparison of unsigned expression >= 0 is always true [-Werror=type-limits]
         const bool selectionValid = !indexes.empty() && indexes.front() >= 0 && indexes.back() < listSize;
                                                         ~~~~~~~~~~~~~~~~^~~~
cc1plus: all warnings being treated as errors
make: *** [GNUmakefile:356: obj/debug-g++/gui-qt/accessor/multilistactions.o] Error 1