Fix unused result warning in File::atomicWrite
---

src/models/common/file.cpp: In function ‘void UnTech::File::atomicWrite(const string&, const void*, size_t)’:
src/models/common/file.cpp:458:14: error: ignoring return value of ‘int chown(const char*, __uid_t, __gid_t)’, declared with attribute warn_unused_result [-Werror=unused-result]
         chown(tmpFilename, statbuf.st_uid, statbuf.st_gid);
         ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~