Fix compiler warning when compiling with g++
    `--> make PROFILE=debug CXX=g++
    g++ -std=c++14 -g -MMD -Isrc -Werror -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC  -D_GLIBCXX_ASSERTIONS -fasynchronous-unwind-tables -fexceptions -fpic -fpie -fstack-protector-strong -pipe -fstack-clash-protection -Wall -Wextra -Wdeprecated -Wduplicated-cond -Wduplicated-branches -Wlogical-op -Wrestrict -Wnull-dereference -Wdouble-promotion -Wformat=2 -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/qt/QtGui -I/usr/include/qt/QtWidgets -DQT_SVG_LIB -I/usr/include/qt/QtSvg -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB  -fPIC -Igen -c -o obj/debug-g++/gui-qt/metatiles/mttileset/mttilesetpropertymanager.o src/gui-qt/metatiles/mttileset/mttilesetpropertymanager.cpp
    src/gui-qt/metatiles/mttileset/mttilesetpropertymanager.cpp: In member function ‘virtual bool UnTech::GuiQt::MetaTiles::MtTilesetPropertyManager::setData(int, const QVariant& ’:
    src/gui-qt/metatiles/mttileset/mttilesetpropertymanager.cpp:153:1: error: control reaches end of non-void function [-Werror=return-type]
     }
     ^
    cc1plus: all warnings being treated as errors
    make: *** [GNUmakefile:347: obj/debug-g++/gui-qt/metatiles/mttileset/mttilesetpropertymanager.o] Error 1