Remove ErrorList::ErrorType enum
Required to compile the editor GUI in mingw.

Why does `wingdi.h` contain `#define ERROR 0` ?

> make PROFILE=mingw obj/mingw/gui/main.o
x86_64-w64-mingw32-g++ -std=c++17 -O2 -flto -MMD -Isrc -D_FORTIFY_SOURCE=2 -D_GLIBCXX_ASSERTIONS -fasynchronous-unwind-tables -fexceptions -fpic -fpie -fstack-protector-strong -pipe -Wall -Wextra -Wdeprecated -Wvla -DIMGUI_IMPL_SDL_OPENGL -DIMGUI_IMPL_OPENGL_LOADER_GL3W -Isrc/vendor/imgui/examples/libs/gl3w -I/usr/include/SDL2 -D_REENTRANT -Isrc/vendor/imgui -c -o obj/mingw/gui/main.o src/gui/main.cpp
In file included from /usr/x86_64-w64-mingw32/include/windows.h:71,
                 from src/vendor/imgui/examples/libs/gl3w/GL/glcorearb.h:60,
                 from src/vendor/imgui/examples/libs/gl3w/GL/gl3w.h:4,
                 from src/gui/opengl/opengl3.h:17,
                 from src/gui/opengl/shaders_opengl3.h:9,
                 from src/gui/shaders.h:10,
                 from src/gui/main.cpp:8:
src/models/common/errorlist.h:51:9: error: expected identifier before numeric constant
   51 |         ERROR
      |         ^~~~~
src/models/common/errorlist.h:51:9: error: expected ‘}’ before numeric constant
In file included from src/models/project/project-data.h:9,
                 from src/gui/untech-editor.h:11,
                 from src/gui/main.cpp:9:
src/models/common/errorlist.h:49:26: note: to match this ‘{’
   49 |     enum class ErrorType {
      |                          ^