Fix QFlags(Zero) is deprecated warnings
g++ -std=c++17 -g -Og -MMD -Isrc -Werror -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC -gsplit-dwarf -D_GLIBCXX_ASSERTIONS -fasynchronous-unwind-tables -fexceptions -fpic -fpie -fstack-protector-strong -pipe -Wall -Wextra -Wdeprecated -Wvla -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/qt/QtGui -I/usr/include/qt/QtWidgets -DQT_SVG_LIB -I/usr/include/qt/QtSvg -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB  -fPIC -Igen -c -o obj/debug-g++/gui-qt/resourcestreemodel.o src/gui-qt/resourcestreemodel.cpp
src/gui-qt/resourcestreemodel.cpp: In member function ‘virtual Qt::ItemFlags UnTech::GuiQt::ResourcesTreeModel::flags(const QModelIndex&) const’:src/gui-qt/resourcestreemodel.cpp:260:16: error: ‘constexpr QFlags<T>::QFlags(QFlags<T>::Zero) [with Enum = Qt::ItemFlag; QFlags<T>::Zero = int QFlags<Qt::ItemFlag>::Private::*]’ is deprecated: Use default constructor instead [-Werror=deprecated-declarations]
  260 |         return 0;
      |                ^
In file included from /usr/include/qt/QtCore/qglobal.h:1302,
                 from /usr/include/qt/QtCore/qatomic.h:41,
                 from /usr/include/qt/QtCore/qvariant.h:43,
                 from /usr/include/qt/QtCore/qabstractitemmodel.h:43,
                 from /usr/include/qt/QtCore/QAbstractItemModel:1,
                 from src/gui-qt/resourcestreemodel.h:11,
                 from src/gui-qt/resourcestreemodel.cpp:7:
/usr/include/qt/QtCore/qflags.h:123:80: note: declared here
  123 |     QT_DEPRECATED_X("Use default constructor instead") Q_DECL_CONSTEXPR inline QFlags(Zero) noexcept : i(0) {}
      |                                                                                ^~~~~~
cc1plus: all warnings being treated as errors
make: *** [GNUmakefile:354: obj/debug-g++/gui-qt/resourcestreemodel.o] Error 1