Fix compiler error when compiling with g++ 8.1.0
I have no idea why this works, but it fixes the error.

Since this is the weirdest compiler error I've encountered, I'm saving it here
for prosperity.

g++ -std=c++14 -O2 -flto -fdata-sections -ffunction-sections -MMD -Isrc -Wall -Wextra -Wdeprecated -Wduplicated-cond -Wduplicated-branches -Wlogical-op -Wrestrict -Wnull-dereference -Wdouble-promotion -Wformat=2 -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/include/qt/QtSvg -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt -I/usr/include/qt/QtGui -I/usr/include/qt -I/usr/include/qt/QtCore -I/usr/include/qt -fPIC -Igen -c -o obj/release/gui-qt/metasprite/metasprite/framedock.o src/gui-qt/metasprite/metasprite/framedock.cpp
In file included from /usr/include/qt/QtGui/qtguiglobal.h:43,
                 from /usr/include/qt/QtWidgets/qtwidgetsglobal.h:43,
                 from /usr/include/qt/QtWidgets/qdockwidget.h:43,
                 from /usr/include/qt/QtWidgets/QDockWidget:1,
                 from src/gui-qt/metasprite/metasprite/framedock.h:11,
                 from src/gui-qt/metasprite/metasprite/framedock.cpp:7:
src/gui-qt/accessor/multipleselectiontableview.h: In instantiation of ‘void UnTech::GuiQt::Accessor::MultipleSelectionTableView::setAccessors(AccessorsT* ...) [with AccessorsT = {UnTech::GuiQt::MetaSprite::MetaSprite::FrameObjectList, UnTech::GuiQt::MetaSprite::MetaSprite::ActionPointList, UnTech::GuiQt::MetaSprite::MetaSprite::EntityHitboxList}]’:
src/gui-qt/metasprite/metasprite/framedock.cpp:127:42:   required from here
src/gui-qt/accessor/multipleselectiontableview.h:113:42: warning: comparison of integer expressions of different signedness: ‘int’ and ‘const size_t’ {aka ‘const long unsigned int’} [-Wsign-compare]
             Q_ASSERT(_actions.add.size() == nAccessors);
/usr/include/qt/QtCore/qglobal.h:738:30: note: in definition of macro ‘Q_ASSERT’
 #    define Q_ASSERT(cond) ((cond) ? static_cast<void>(0) : qt_assert(#cond, __FILE__, __LINE__))
                              ^~~~
In file included from gen/gui-qt/metasprite/metasprite/framedock.ui.h:28,
                 from src/gui-qt/metasprite/metasprite/framedock.cpp:15:
src/gui-qt/accessor/multipleselectiontableview.h:134:54: error: use of ‘this’ in a constant expression
             std::array<ListActionStatus, nAccessors> status = { ListActionHelper::status(accessors)... };
                                                      ^~~~~~
src/gui-qt/accessor/multipleselectiontableview.h:134:54: note: in template argument for type ‘long unsigned int’
src/gui-qt/accessor/multipleselectiontableview.h:134:54: error: use of ‘this’ in a constant expression
src/gui-qt/accessor/multipleselectiontableview.h:134:54: note: in template argument for type ‘long unsigned int’
src/gui-qt/accessor/multipleselectiontableview.h:261:24: error: ‘static void UnTech::GuiQt::Accessor::MultipleSelectionTableView::for_each(Functor&&, AccessorsT* ...) [with Functor = UnTech::GuiQt::Accessor::MultipleSelectionTableView::setAccessors(AccessorsT* ...) [with AccessorsT = {UnTech::GuiQt::MetaSprite::MetaSprite::FrameObjectList, UnTech::GuiQt::MetaSprite::MetaSprite::ActionPointList, UnTech::GuiQt::MetaSprite::MetaSprite::EntityHitboxList}]::<lambda(auto:8*)>&; AccessorsT = {UnTech::GuiQt::MetaSprite::MetaSprite::FrameObjectList, UnTech::GuiQt::MetaSprite::MetaSprite::ActionPointList, UnTech::GuiQt::MetaSprite::MetaSprite::EntityHitboxList}]’, declared using local type ‘UnTech::GuiQt::Accessor::MultipleSelectionTableView::setAccessors(AccessorsT* ...) [with AccessorsT = {UnTech::GuiQt::MetaSprite::MetaSprite::FrameObjectList, UnTech::GuiQt::MetaSprite::MetaSprite::ActionPointList, UnTech::GuiQt::MetaSprite::MetaSprite::EntityHitboxList}]::<lambda(auto:8*)>’, is used but never defined [-fpermissive]
     inline static void for_each(Functor&& functor, AccessorsT*... accessors)
                        ^~~~~~~~
In file included from /usr/include/qt/QtWidgets/qwidget.h:45,
                 from /usr/include/qt/QtWidgets/qdockwidget.h:44,
                 from /usr/include/qt/QtWidgets/QDockWidget:1,
                 from src/gui-qt/metasprite/metasprite/framedock.h:11,
                 from src/gui-qt/metasprite/metasprite/framedock.cpp:7:
/usr/include/qt/QtCore/qobject.h:314:13: error: ‘static typename std::enable_if<(QtPrivate::FunctionPointer<Func2>::ArgumentCount == -1), QMetaObject::Connection>::type QObject::connect(const typename QtPrivate::FunctionPointer<Func>::Object*, Func1, const QObject*, Func2, Qt::ConnectionType) [with Func1 = void (QItemSelectionModel::*)(const QItemSelection&, const QItemSelection&); Func2 = UnTech::GuiQt::Accessor::MultipleSelectionTableView::setAccessors(AccessorsT* ...) [with AccessorsT = {UnTech::GuiQt::MetaSprite::MetaSprite::FrameObjectList, UnTech::GuiQt::MetaSprite::MetaSprite::ActionPointList, UnTech::GuiQt::MetaSprite::MetaSprite::EntityHitboxList}]::<lambda()>; typename std::enable_if<(QtPrivate::FunctionPointer<Func2>::ArgumentCount == -1), QMetaObject::Connection>::type = QMetaObject::Connection; typename QtPrivate::FunctionPointer<Func>::Object = QItemSelectionModel]’, declared using local type ‘UnTech::GuiQt::Accessor::MultipleSelectionTableView::setAccessors(AccessorsT* ...) [with AccessorsT = {UnTech::GuiQt::MetaSprite::MetaSprite::FrameObjectList, UnTech::GuiQt::MetaSprite::MetaSprite::ActionPointList, UnTech::GuiQt::MetaSprite::MetaSprite::EntityHitboxList}]::<lambda()>’, is used but never defined [-fpermissive]
             connect(const typename QtPrivate::FunctionPointer<Func1>::Object *sender, Func1 signal, const QObject *context, Func2 slot,
             ^~~~~~~
In file included from gen/gui-qt/metasprite/metasprite/framedock.ui.h:28,
                 from src/gui-qt/metasprite/metasprite/framedock.cpp:15:
src/gui-qt/accessor/multipleselectiontableview.h:281:24: error: ‘static void UnTech::GuiQt::Accessor::MultipleSelectionTableView::for_each_i(Functor&&, AccessorsT* ...) [with Functor = UnTech::GuiQt::Accessor::MultipleSelectionTableView::setAccessors(AccessorsT* ...) [with AccessorsT = {UnTech::GuiQt::MetaSprite::MetaSprite::FrameObjectList, UnTech::GuiQt::MetaSprite::MetaSprite::ActionPointList, UnTech::GuiQt::MetaSprite::MetaSprite::EntityHitboxList}]::<lambda(auto:9*, int)>&; AccessorsT = {UnTech::GuiQt::MetaSprite::MetaSprite::FrameObjectList, UnTech::GuiQt::MetaSprite::MetaSprite::ActionPointList, UnTech::GuiQt::MetaSprite::MetaSprite::EntityHitboxList}]’, declared using local type ‘UnTech::GuiQt::Accessor::MultipleSelectionTableView::setAccessors(AccessorsT* ...) [with AccessorsT = {UnTech::GuiQt::MetaSprite::MetaSprite::FrameObjectList, UnTech::GuiQt::MetaSprite::MetaSprite::ActionPointList, UnTech::GuiQt::MetaSprite::MetaSprite::EntityHitboxList}]::<lambda(auto:9*, int)>’, is used but never defined [-fpermissive]
     inline static void for_each_i(Functor&& functor, AccessorsT*... accessors)
                        ^~~~~~~~~~
src/gui-qt/accessor/multipleselectiontableview.h:261:24: error: ‘static void UnTech::GuiQt::Accessor::MultipleSelectionTableView::for_each(Functor&&, AccessorsT* ...) [with Functor = UnTech::GuiQt::Accessor::MultipleSelectionTableView::setAccessors(AccessorsT* ...) [with AccessorsT = {UnTech::GuiQt::MetaSprite::MetaSprite::FrameObjectList, UnTech::GuiQt::MetaSprite::MetaSprite::ActionPointList, UnTech::GuiQt::MetaSprite::MetaSprite::EntityHitboxList}]::<lambda()>::<lambda(auto:11*)>&; AccessorsT = {UnTech::GuiQt::MetaSprite::MetaSprite::FrameObjectList, UnTech::GuiQt::MetaSprite::MetaSprite::ActionPointList, UnTech::GuiQt::MetaSprite::MetaSprite::EntityHitboxList}]’, declared using local type ‘UnTech::GuiQt::Accessor::MultipleSelectionTableView::setAccessors(AccessorsT* ...) [with AccessorsT = {UnTech::GuiQt::MetaSprite::MetaSprite::FrameObjectList, UnTech::GuiQt::MetaSprite::MetaSprite::ActionPointList, UnTech::GuiQt::MetaSprite::MetaSprite::EntityHitboxList}]::<lambda()>::<lambda(auto:11*)>’, is used but never defined [-fpermissive]
     inline static void for_each(Functor&& functor, AccessorsT*... accessors)
                        ^~~~~~~~
In file included from /usr/include/qt/QtWidgets/qwidget.h:45,
                 from /usr/include/qt/QtWidgets/qdockwidget.h:44,
                 from /usr/include/qt/QtWidgets/QDockWidget:1,
                 from src/gui-qt/metasprite/metasprite/framedock.h:11,
                 from src/gui-qt/metasprite/metasprite/framedock.cpp:7:
/usr/include/qt/QtCore/qobject.h:314:13: error: ‘static typename std::enable_if<(QtPrivate::FunctionPointer<Func2>::ArgumentCount == -1), QMetaObject::Connection>::type QObject::connect(const typename QtPrivate::FunctionPointer<Func>::Object*, Func1, const QObject*, Func2, Qt::ConnectionType) [with Func1 = void (QAction::*)(bool); Func2 = UnTech::GuiQt::Accessor::MultipleSelectionTableView::setAccessors(AccessorsT* ...) [with AccessorsT = {UnTech::GuiQt::MetaSprite::MetaSprite::FrameObjectList, UnTech::GuiQt::MetaSprite::MetaSprite::ActionPointList, UnTech::GuiQt::MetaSprite::MetaSprite::EntityHitboxList}]::<lambda()>; typename std::enable_if<(QtPrivate::FunctionPointer<Func2>::ArgumentCount == -1), QMetaObject::Connection>::type = QMetaObject::Connection; typename QtPrivate::FunctionPointer<Func>::Object = QAction]’, declared using local type ‘UnTech::GuiQt::Accessor::MultipleSelectionTableView::setAccessors(AccessorsT* ...) [with AccessorsT = {UnTech::GuiQt::MetaSprite::MetaSprite::FrameObjectList, UnTech::GuiQt::MetaSprite::MetaSprite::ActionPointList, UnTech::GuiQt::MetaSprite::MetaSprite::EntityHitboxList}]::<lambda()>’, is used but never defined [-fpermissive]
             connect(const typename QtPrivate::FunctionPointer<Func1>::Object *sender, Func1 signal, const QObject *context, Func2 slot,
             ^~~~~~~
In file included from gen/gui-qt/metasprite/metasprite/framedock.ui.h:28,
                 from src/gui-qt/metasprite/metasprite/framedock.cpp:15:
src/gui-qt/accessor/multipleselectiontableview.h:261:24: error: ‘static void UnTech::GuiQt::Accessor::MultipleSelectionTableView::for_each(Functor&&, AccessorsT* ...) [with Functor = UnTech::GuiQt::Accessor::MultipleSelectionTableView::setAccessors(AccessorsT* ...) [with AccessorsT = {UnTech::GuiQt::MetaSprite::MetaSprite::FrameObjectList, UnTech::GuiQt::MetaSprite::MetaSprite::ActionPointList, UnTech::GuiQt::MetaSprite::MetaSprite::EntityHitboxList}]::<lambda()>::<lambda(auto:12*)>&; AccessorsT = {UnTech::GuiQt::MetaSprite::MetaSprite::FrameObjectList, UnTech::GuiQt::MetaSprite::MetaSprite::ActionPointList, UnTech::GuiQt::MetaSprite::MetaSprite::EntityHitboxList}]’, declared using local type ‘UnTech::GuiQt::Accessor::MultipleSelectionTableView::setAccessors(AccessorsT* ...) [with AccessorsT = {UnTech::GuiQt::MetaSprite::MetaSprite::FrameObjectList, UnTech::GuiQt::MetaSprite::MetaSprite::ActionPointList, UnTech::GuiQt::MetaSprite::MetaSprite::EntityHitboxList}]::<lambda()>::<lambda(auto:12*)>’, is used but never defined [-fpermissive]
     inline static void for_each(Functor&& functor, AccessorsT*... accessors)
                        ^~~~~~~~
In file included from /usr/include/qt/QtWidgets/qwidget.h:45,
                 from /usr/include/qt/QtWidgets/qdockwidget.h:44,
                 from /usr/include/qt/QtWidgets/QDockWidget:1,
                 from src/gui-qt/metasprite/metasprite/framedock.h:11,
                 from src/gui-qt/metasprite/metasprite/framedock.cpp:7:
/usr/include/qt/QtCore/qobject.h:314:13: error: ‘static typename std::enable_if<(QtPrivate::FunctionPointer<Func2>::ArgumentCount == -1), QMetaObject::Connection>::type QObject::connect(const typename QtPrivate::FunctionPointer<Func>::Object*, Func1, const QObject*, Func2, Qt::ConnectionType) [with Func1 = void (QAction::*)(bool); Func2 = UnTech::GuiQt::Accessor::MultipleSelectionTableView::setAccessors(AccessorsT* ...) [with AccessorsT = {UnTech::GuiQt::MetaSprite::MetaSprite::FrameObjectList, UnTech::GuiQt::MetaSprite::MetaSprite::ActionPointList, UnTech::GuiQt::MetaSprite::MetaSprite::EntityHitboxList}]::<lambda()>; typename std::enable_if<(QtPrivate::FunctionPointer<Func2>::ArgumentCount == -1), QMetaObject::Connection>::type = QMetaObject::Connection; typename QtPrivate::FunctionPointer<Func>::Object = QAction]’, declared using local type ‘UnTech::GuiQt::Accessor::MultipleSelectionTableView::setAccessors(AccessorsT* ...) [with AccessorsT = {UnTech::GuiQt::MetaSprite::MetaSprite::FrameObjectList, UnTech::GuiQt::MetaSprite::MetaSprite::ActionPointList, UnTech::GuiQt::MetaSprite::MetaSprite::EntityHitboxList}]::<lambda()>’, is used but never defined [-fpermissive]
             connect(const typename QtPrivate::FunctionPointer<Func1>::Object *sender, Func1 signal, const QObject *context, Func2 slot,
             ^~~~~~~
In file included from gen/gui-qt/metasprite/metasprite/framedock.ui.h:28,
                 from src/gui-qt/metasprite/metasprite/framedock.cpp:15:
src/gui-qt/accessor/multipleselectiontableview.h:261:24: error: ‘static void UnTech::GuiQt::Accessor::MultipleSelectionTableView::for_each(Functor&&, AccessorsT* ...) [with Functor = UnTech::GuiQt::Accessor::MultipleSelectionTableView::setAccessors(AccessorsT* ...) [with AccessorsT = {UnTech::GuiQt::MetaSprite::MetaSprite::FrameObjectList, UnTech::GuiQt::MetaSprite::MetaSprite::ActionPointList, UnTech::GuiQt::MetaSprite::MetaSprite::EntityHitboxList}]::<lambda()>::<lambda(auto:13*)>&; AccessorsT = {UnTech::GuiQt::MetaSprite::MetaSprite::FrameObjectList, UnTech::GuiQt::MetaSprite::MetaSprite::ActionPointList, UnTech::GuiQt::MetaSprite::MetaSprite::EntityHitboxList}]’, declared using local type ‘UnTech::GuiQt::Accessor::MultipleSelectionTableView::setAccessors(AccessorsT* ...) [with AccessorsT = {UnTech::GuiQt::MetaSprite::MetaSprite::FrameObjectList, UnTech::GuiQt::MetaSprite::MetaSprite::ActionPointList, UnTech::GuiQt::MetaSprite::MetaSprite::EntityHitboxList}]::<lambda()>::<lambda(auto:13*)>’, is used but never defined [-fpermissive]
     inline static void for_each(Functor&& functor, AccessorsT*... accessors)
                        ^~~~~~~~
In file included from /usr/include/qt/QtWidgets/qwidget.h:45,
                 from /usr/include/qt/QtWidgets/qdockwidget.h:44,
                 from /usr/include/qt/QtWidgets/QDockWidget:1,
                 from src/gui-qt/metasprite/metasprite/framedock.h:11,
                 from src/gui-qt/metasprite/metasprite/framedock.cpp:7:
/usr/include/qt/QtCore/qobject.h:314:13: error: ‘static typename std::enable_if<(QtPrivate::FunctionPointer<Func2>::ArgumentCount == -1), QMetaObject::Connection>::type QObject::connect(const typename QtPrivate::FunctionPointer<Func>::Object*, Func1, const QObject*, Func2, Qt::ConnectionType) [with Func1 = void (QAction::*)(bool); Func2 = UnTech::GuiQt::Accessor::MultipleSelectionTableView::setAccessors(AccessorsT* ...) [with AccessorsT = {UnTech::GuiQt::MetaSprite::MetaSprite::FrameObjectList, UnTech::GuiQt::MetaSprite::MetaSprite::ActionPointList, UnTech::GuiQt::MetaSprite::MetaSprite::EntityHitboxList}]::<lambda()>; typename std::enable_if<(QtPrivate::FunctionPointer<Func2>::ArgumentCount == -1), QMetaObject::Connection>::type = QMetaObject::Connection; typename QtPrivate::FunctionPointer<Func>::Object = QAction]’, declared using local type ‘UnTech::GuiQt::Accessor::MultipleSelectionTableView::setAccessors(AccessorsT* ...) [with AccessorsT = {UnTech::GuiQt::MetaSprite::MetaSprite::FrameObjectList, UnTech::GuiQt::MetaSprite::MetaSprite::ActionPointList, UnTech::GuiQt::MetaSprite::MetaSprite::EntityHitboxList}]::<lambda()>’, is used but never defined [-fpermissive]
             connect(const typename QtPrivate::FunctionPointer<Func1>::Object *sender, Func1 signal, const QObject *context, Func2 slot,
             ^~~~~~~
In file included from gen/gui-qt/metasprite/metasprite/framedock.ui.h:28,
                 from src/gui-qt/metasprite/metasprite/framedock.cpp:15:
src/gui-qt/accessor/multipleselectiontableview.h:261:24: error: ‘static void UnTech::GuiQt::Accessor::MultipleSelectionTableView::for_each(Functor&&, AccessorsT* ...) [with Functor = UnTech::GuiQt::Accessor::MultipleSelectionTableView::setAccessors(AccessorsT* ...) [with AccessorsT = {UnTech::GuiQt::MetaSprite::MetaSprite::FrameObjectList, UnTech::GuiQt::MetaSprite::MetaSprite::ActionPointList, UnTech::GuiQt::MetaSprite::MetaSprite::EntityHitboxList}]::<lambda()>::<lambda(auto:14*)>&; AccessorsT = {UnTech::GuiQt::MetaSprite::MetaSprite::FrameObjectList, UnTech::GuiQt::MetaSprite::MetaSprite::ActionPointList, UnTech::GuiQt::MetaSprite::MetaSprite::EntityHitboxList}]’, declared using local type ‘UnTech::GuiQt::Accessor::MultipleSelectionTableView::setAccessors(AccessorsT* ...) [with AccessorsT = {UnTech::GuiQt::MetaSprite::MetaSprite::FrameObjectList, UnTech::GuiQt::MetaSprite::MetaSprite::ActionPointList, UnTech::GuiQt::MetaSprite::MetaSprite::EntityHitboxList}]::<lambda()>::<lambda(auto:14*)>’, is used but never defined [-fpermissive]
     inline static void for_each(Functor&& functor, AccessorsT*... accessors)
                        ^~~~~~~~
In file included from /usr/include/qt/QtWidgets/qwidget.h:45,
                 from /usr/include/qt/QtWidgets/qdockwidget.h:44,
                 from /usr/include/qt/QtWidgets/QDockWidget:1,
                 from src/gui-qt/metasprite/metasprite/framedock.h:11,
                 from src/gui-qt/metasprite/metasprite/framedock.cpp:7:
/usr/include/qt/QtCore/qobject.h:314:13: error: ‘static typename std::enable_if<(QtPrivate::FunctionPointer<Func2>::ArgumentCount == -1), QMetaObject::Connection>::type QObject::connect(const typename QtPrivate::FunctionPointer<Func>::Object*, Func1, const QObject*, Func2, Qt::ConnectionType) [with Func1 = void (QAction::*)(bool); Func2 = UnTech::GuiQt::Accessor::MultipleSelectionTableView::setAccessors(AccessorsT* ...) [with AccessorsT = {UnTech::GuiQt::MetaSprite::MetaSprite::FrameObjectList, UnTech::GuiQt::MetaSprite::MetaSprite::ActionPointList, UnTech::GuiQt::MetaSprite::MetaSprite::EntityHitboxList}]::<lambda()>; typename std::enable_if<(QtPrivate::FunctionPointer<Func2>::ArgumentCount == -1), QMetaObject::Connection>::type = QMetaObject::Connection; typename QtPrivate::FunctionPointer<Func>::Object = QAction]’, declared using local type ‘UnTech::GuiQt::Accessor::MultipleSelectionTableView::setAccessors(AccessorsT* ...) [with AccessorsT = {UnTech::GuiQt::MetaSprite::MetaSprite::FrameObjectList, UnTech::GuiQt::MetaSprite::MetaSprite::ActionPointList, UnTech::GuiQt::MetaSprite::MetaSprite::EntityHitboxList}]::<lambda()>’, is used but never defined [-fpermissive]
             connect(const typename QtPrivate::FunctionPointer<Func1>::Object *sender, Func1 signal, const QObject *context, Func2 slot,
             ^~~~~~~
make: *** [GNUmakefile:279: obj/release/gui-qt/metasprite/metasprite/framedock.o] Error 1