Fix missing initializer warning
g++ -std=c++17 -g -Og -MMD -Isrc -Werror -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC -gsplit-dwarf -D_GLIBCXX_ASSERTIONS -fasynchronous-unwind-tables -fexceptions -fpic -fpie -fstack-protector-strong -pipe -Wall -Wextra -Wdeprecated -Wvla -I/usr/include/qt/QtCore -I/usr/include/qt -I/usr/include/qt/QtGui -I/usr/include/qt/QtWidgets -DQT_SVG_LIB -I/usr/include/qt/QtSvg -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB  -fPIC -Igen -c -o obj/debug-g++/gui-qt/rooms/accessors.o src/gui-qt/rooms/accessors.cpp
src/gui-qt/rooms/accessors.cpp: In member function ‘bool UnTech::GuiQt::Rooms::EntityEntriesList::addEntity(UnTech::GuiQt::Accessor::NestedNlvMulitpleSelectionAccessor<UnTech::Rooms::EntityGroup, UnTech::Rooms::EntityEntry, UnTech::GuiQt::Rooms::ResourceItem>::index_type, const UnTech::idstring&, const point&)’:
src/gui-qt/rooms/accessors.cpp:215:47: error: missing initializer for member ‘UnTech::Rooms::EntityEntry::parameter’ [-Werror=missing-field-initializers]
  215 |                          .position = position },
      |                                               ^
cc1plus: all warnings being treated as errors
make: *** [GNUmakefile:354: obj/debug-g++/gui-qt/rooms/accessors.o] Error 1